version: '3.8'

services:
  db-parcels:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parcels_db
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-cheques:
    image: postgres:latest
    container_name: cheques_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheques_db
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka-native:3.8.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  billing:
    build:
      context: ./billing
      dockerfile: Dockerfile
    container_name: billing
    ports:
      - "9993:8080"
    networks:
      - app-network
    depends_on:
      - edu_app

  consoleapp:
    build:
      context: ./consoleapp
      dockerfile: Dockerfile
    container_name: consoleapp
    ports:
      - "9991:8081"
    networks:
      - app-network
    depends_on:
      - edu_app

  telegrambot:
    build:
      context: ./telegrambot
      dockerfile: Dockerfile
    container_name: telegrambot
    ports:
      - "9990:8082"
    networks:
      - app-network
    depends_on:
      - edu_app

  edu_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu_app
    ports:
      - "9992:8083"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge