spring:
  datasource:
    url: jdbc:postgresql://localhost:7777/parcels_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        calculate-cheque-topic:
          destination: calculate-cheque-topic
          content-type: application/json
          group: billing
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      client-id: "billing"

server:
  port: 9992

springdoc:
  swagger-ui:
    enabled: true