spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/cheques_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 9993

cheque:
  load-cost: 80
  unload-cost: 50